"""The deterministic daily Gmail digest: frozen into SQLite (5.4A), then sent (5.4B).

Phase 5.4A assembles one email a day from the audited Portfolio snapshot,
renders it, gives it an identity and stores it. Phase 5.4B is transport and
only transport: it takes the subject and the two bodies exactly as that row
froze them, wraps them in a MIME message, and hands them to Gmail through an
OAuth authorization that grants ``gmail.send`` and nothing else. It never
rebuilds a digest, never re-reads a Portfolio, and never re-decides anything.

There is no mailbox reading anywhere in this package — no ``gmail.readonly``,
no ``gmail.modify``, no ``gmail.metadata``, no ``mail.google.com`` — and no
scheduler: a person runs a command, one pass happens, the process exits. Gmail
Intelligence, which reads and classifies mail, is Phase 7 and needs its own
consent rather than a scope widened here.
"""

from .delivery import GmailDeliveryDrainResult, drain_gmail_digests
from .delivery_persistence import (
    AUTHORIZATION_ERROR_CODE,
    CLAIM_LEASE_SECONDS,
    MAX_DELIVERY_ATTEMPTS,
    MISSING_MESSAGE_ID_CODE,
    RETRY_BACKOFF_SECONDS,
    RETRY_LIMIT_EXHAUSTED_PREFIX,
    TERMINAL_STATUSES,
    TRANSPORT_ERROR_CODE,
    ClaimedDigest,
    DeliverySettlement,
    GmailDeliveryError,
    GmailDeliveryErrorCategory,
    GmailDeliveryStatusReport,
    GmailSendOutcome,
    authorization_failure,
    bounded_error_code,
    claim_due_digest,
    count_recipient_mismatched_due,
    delivered,
    exhausted_error_code,
    new_claim_token,
    read_delivery_status,
    record_delivery_failure,
    record_delivery_success,
    recover_stale_claims,
    release_delivery_claim,
    retry_delay_seconds,
    transport_failure,
)
from .message import (
    build_digest_message,
    build_raw_digest_message,
    encode_raw_message,
)
from .oauth import (
    DEFAULT_CLIENT_SECRET_PATH,
    DEFAULT_TOKEN_PATH,
    FORBIDDEN_SCOPES,
    GMAIL_SEND_SCOPE,
    GMAIL_SEND_SCOPES,
    GmailOAuthConfiguration,
    GmailOAuthError,
    build_gmail_service,
    load_send_credentials,
    validate_client_configuration,
    validate_send_only_scope,
    write_token_document,
)
from .sender import (
    GmailDigestSender,
    GmailMessageTransport,
    GoogleApiGmailTransport,
    build_gmail_digest_sender,
    classify_gmail_status,
    classify_send_exception,
    error_reasons,
)
from .assembly import (
    ALLOWED_URL_SCHEMES,
    build_digest_items,
    digest_sort_key,
    read_digest_opportunity_facts,
    validate_digest_url,
)
from .fingerprint import (
    canonical_digest_payload,
    digest_content_fingerprint,
    normalize_recipient,
    recipient_fingerprint,
)
from .local_day import LocalDay, resolve_local_day, resolve_timezone
from .materialize import (
    audited_current_run,
    build_digest_candidate,
    materialize_daily_digest,
    now_timestamp,
    preview_digest_decision,
)
from .models import (
    BUCKET_ORDER,
    DIGEST_VERSION,
    PRIORITY_ORDER,
    DigestCandidate,
    DigestContent,
    DigestDecisionPreview,
    DigestItem,
    DigestMaterializationResult,
    DigestMaterializationStatus,
    DigestOutboxRecord,
    DigestStatusReport,
    GmailDigestError,
    GmailDigestStatus,
)
from .persistence import (
    DIGEST_OUTBOX_TABLE,
    REQUIRED_MIGRATION_VERSION,
    insert_frozen_digest,
    read_digest_for_day,
    read_digest_status,
    read_latest_sent_digest,
)
from .rendering import (
    BUCKET_LABELS,
    UNKNOWN_LOCATION_LABEL,
    render_digest,
    render_html,
    render_subject,
    render_text,
)

__all__ = [
    "ALLOWED_URL_SCHEMES",
    "AUTHORIZATION_ERROR_CODE",
    "BUCKET_LABELS",
    "BUCKET_ORDER",
    "CLAIM_LEASE_SECONDS",
    "ClaimedDigest",
    "DEFAULT_CLIENT_SECRET_PATH",
    "DEFAULT_TOKEN_PATH",
    "DIGEST_OUTBOX_TABLE",
    "DIGEST_VERSION",
    "DeliverySettlement",
    "DigestCandidate",
    "DigestContent",
    "DigestDecisionPreview",
    "DigestItem",
    "DigestMaterializationResult",
    "DigestMaterializationStatus",
    "DigestOutboxRecord",
    "DigestStatusReport",
    "FORBIDDEN_SCOPES",
    "GMAIL_SEND_SCOPE",
    "GMAIL_SEND_SCOPES",
    "GmailDeliveryDrainResult",
    "GmailDeliveryError",
    "GmailDeliveryErrorCategory",
    "GmailDeliveryStatusReport",
    "GmailDigestError",
    "GmailDigestSender",
    "GmailDigestStatus",
    "GmailMessageTransport",
    "GmailOAuthConfiguration",
    "GmailOAuthError",
    "GmailSendOutcome",
    "GoogleApiGmailTransport",
    "LocalDay",
    "MAX_DELIVERY_ATTEMPTS",
    "MISSING_MESSAGE_ID_CODE",
    "PRIORITY_ORDER",
    "REQUIRED_MIGRATION_VERSION",
    "RETRY_BACKOFF_SECONDS",
    "RETRY_LIMIT_EXHAUSTED_PREFIX",
    "TERMINAL_STATUSES",
    "TRANSPORT_ERROR_CODE",
    "UNKNOWN_LOCATION_LABEL",
    "audited_current_run",
    "authorization_failure",
    "bounded_error_code",
    "build_digest_candidate",
    "build_digest_items",
    "build_digest_message",
    "build_gmail_digest_sender",
    "build_gmail_service",
    "build_raw_digest_message",
    "canonical_digest_payload",
    "claim_due_digest",
    "classify_gmail_status",
    "classify_send_exception",
    "count_recipient_mismatched_due",
    "delivered",
    "digest_content_fingerprint",
    "digest_sort_key",
    "drain_gmail_digests",
    "encode_raw_message",
    "error_reasons",
    "exhausted_error_code",
    "insert_frozen_digest",
    "load_send_credentials",
    "materialize_daily_digest",
    "new_claim_token",
    "normalize_recipient",
    "now_timestamp",
    "preview_digest_decision",
    "read_delivery_status",
    "read_digest_for_day",
    "read_digest_opportunity_facts",
    "read_digest_status",
    "read_latest_sent_digest",
    "recipient_fingerprint",
    "record_delivery_failure",
    "record_delivery_success",
    "recover_stale_claims",
    "release_delivery_claim",
    "render_digest",
    "render_html",
    "render_subject",
    "render_text",
    "resolve_local_day",
    "resolve_timezone",
    "retry_delay_seconds",
    "transport_failure",
    "validate_client_configuration",
    "validate_digest_url",
    "validate_send_only_scope",
    "write_token_document",
]
