"""Notification foundations for Opportunity Radar AI.

Phase 5.3A owns the browser push subscriptions a user opts into. Phase 5.3B
adds the notification policy: which movements of the audited Portfolio deserve
a notification, the append-only events those movements produce, and the outbox
a later phase will drain. Phase 5.3C1 drains it: it freezes the recipients of
each outbox row, sends the payload the event already describes over Web Push,
and records every attempt, retry, and revocation.
"""

from services.notifications.delivery import (
    DeliveryDrainResult,
    WebPushDeliverySender,
    drain_notification_deliveries,
    materialize_notification_deliveries,
)
from services.notifications.delivery_payload import (
    DELIVERY_PAYLOAD_VERSION,
    NotificationPayloadError,
    build_push_payload,
    encode_push_payload,
)
from services.notifications.delivery_persistence import (
    CLAIM_LEASE_SECONDS,
    MAX_DELIVERY_ATTEMPTS,
    RETRY_BACKOFF_SECONDS,
    AttemptResult,
    ClaimedTarget,
    DeliveryBatchStatus,
    DeliveryErrorCategory,
    DeliveryOutcome,
    DeliveryStatusReport,
    DeliveryTargetStatus,
    MaterializationResult,
    NotificationDeliveryError,
    claim_due_targets,
    claim_next_due_target,
    classify_status_code,
    close_targets_of_revoked_subscriptions,
    materialize_delivery_batches,
    new_claim_token,
    read_delivery_status,
    record_delivery_attempt,
    recover_stale_claims,
    release_delivery_claim,
    retry_delay_seconds,
    transport_failure,
)
from services.notifications.fingerprint import (
    canonical_notification_event_payload,
    notification_event_fingerprint,
)
from services.notifications.opportunity_metadata import (
    NotificationMetadataError,
    read_opportunity_metadata,
)
from services.notifications.persistence import (
    NotificationEventRecord,
    NotificationPersistenceError,
    NotificationStoreResult,
    store_notification_events,
)
from services.notifications.policy import (
    ESCALATIONS,
    NOTIFICATION_POLICY_VERSION,
    NOTIFICATION_TARGET_PATH,
    NotificationEventType,
    NotificationTransition,
    OpportunityNotificationMetadata,
    PortfolioPosition,
    evaluate_transition,
    evaluate_transitions,
)
from services.notifications.push_subscriptions import (
    AUTH_BYTE_LENGTH,
    MAX_ENDPOINT_LENGTH,
    MAX_KEY_LENGTH,
    P256DH_BYTE_LENGTH,
    P256DH_UNCOMPRESSED_PREFIX,
    PushSubscriptionError,
    PushSubscriptionOwnershipError,
    PushSubscriptionStatus,
    SubscribeResult,
    UnsubscribeResult,
    decode_base64url,
    revoke_push_subscription_by_id,
    subscribe_push_subscription,
    unsubscribe_push_subscription,
    valid_auth,
    valid_p256dh,
)
from services.notifications.web_push import (
    DEFAULT_TTL_SECONDS,
    MAX_PAYLOAD_BYTES,
    VAPID_PRIVATE_KEY_VARIABLE,
    VAPID_PUBLIC_KEY_VARIABLE,
    VAPID_SUBJECT_VARIABLE,
    HttpxWebPushTransport,
    PushTarget,
    VapidConfiguration,
    WebPushConfigurationError,
    WebPushError,
    WebPushRequest,
    WebPushResponse,
    WebPushTransport,
    WebPushTransportError,
    build_vapid_configuration,
    build_web_push_request,
    encrypt_push_message,
    load_vapid_configuration,
)
from services.notifications.sync import (
    NotificationSyncError,
    NotificationSyncResult,
    NotificationSyncStatus,
    sync_notification_policy,
)

__all__ = [
    "AUTH_BYTE_LENGTH",
    "AttemptResult",
    "CLAIM_LEASE_SECONDS",
    "ClaimedTarget",
    "DEFAULT_TTL_SECONDS",
    "DELIVERY_PAYLOAD_VERSION",
    "DeliveryBatchStatus",
    "DeliveryDrainResult",
    "DeliveryErrorCategory",
    "DeliveryOutcome",
    "DeliveryStatusReport",
    "DeliveryTargetStatus",
    "ESCALATIONS",
    "HttpxWebPushTransport",
    "MAX_DELIVERY_ATTEMPTS",
    "MAX_ENDPOINT_LENGTH",
    "MAX_KEY_LENGTH",
    "MAX_PAYLOAD_BYTES",
    "MaterializationResult",
    "NOTIFICATION_POLICY_VERSION",
    "NOTIFICATION_TARGET_PATH",
    "NotificationDeliveryError",
    "NotificationEventRecord",
    "NotificationEventType",
    "NotificationMetadataError",
    "NotificationPayloadError",
    "NotificationPersistenceError",
    "NotificationStoreResult",
    "NotificationSyncError",
    "NotificationSyncResult",
    "NotificationSyncStatus",
    "NotificationTransition",
    "OpportunityNotificationMetadata",
    "P256DH_BYTE_LENGTH",
    "P256DH_UNCOMPRESSED_PREFIX",
    "PortfolioPosition",
    "PushSubscriptionError",
    "PushSubscriptionOwnershipError",
    "PushSubscriptionStatus",
    "PushTarget",
    "RETRY_BACKOFF_SECONDS",
    "SubscribeResult",
    "UnsubscribeResult",
    "VAPID_PRIVATE_KEY_VARIABLE",
    "VAPID_PUBLIC_KEY_VARIABLE",
    "VAPID_SUBJECT_VARIABLE",
    "VapidConfiguration",
    "WebPushConfigurationError",
    "WebPushDeliverySender",
    "WebPushError",
    "WebPushRequest",
    "WebPushResponse",
    "WebPushTransport",
    "WebPushTransportError",
    "build_push_payload",
    "build_vapid_configuration",
    "build_web_push_request",
    "canonical_notification_event_payload",
    "claim_due_targets",
    "claim_next_due_target",
    "classify_status_code",
    "close_targets_of_revoked_subscriptions",
    "decode_base64url",
    "drain_notification_deliveries",
    "encode_push_payload",
    "encrypt_push_message",
    "evaluate_transition",
    "evaluate_transitions",
    "load_vapid_configuration",
    "materialize_delivery_batches",
    "materialize_notification_deliveries",
    "new_claim_token",
    "notification_event_fingerprint",
    "read_delivery_status",
    "read_opportunity_metadata",
    "record_delivery_attempt",
    "recover_stale_claims",
    "release_delivery_claim",
    "retry_delay_seconds",
    "revoke_push_subscription_by_id",
    "store_notification_events",
    "subscribe_push_subscription",
    "sync_notification_policy",
    "transport_failure",
    "unsubscribe_push_subscription",
    "valid_auth",
    "valid_p256dh",
]
