import "server-only";

const API_BASE = "http://127.0.0.1:8000";
export type PortfolioBucket = "SAFE" | "TARGET" | "AMBITIOUS";
export type PortfolioDisposition = "INCLUDED" | "EXCLUDED";
export type PortfolioItem = { opportunity_id:number; opportunity:{id:number;canonical_title:string;organization:string;location:string|null;last_seen_at:string;original_url:string}; portfolio:{disposition:PortfolioDisposition;bucket:PortfolioBucket|null;priority_category:"URGENT"|"HIGH"|"MEDIUM"|"LOW"|"IGNORE"|null;eligibility_status:"ELIGIBLE"|"UNKNOWN"|"INELIGIBLE";matching_lane:"PRIMARY"|"UNCERTAIN"|"OUTSIDE_PREFERENCES";required_skill_score:number|null;required_skill_matched_count:number;required_skill_total_count:number;safe_cap_applied:boolean;reason_codes:string[];assessment_fingerprint:string;explanation:Record<string,unknown>} };
export type PortfolioRun = {run_id:number;priority_run_id:number;matching_run_id:number;created_at:string;assessment_count:number;included_count:number;excluded_count:number;bucket_counts:Record<PortfolioBucket,number>;persistence_version:string;input_assembly_version:string;portfolio_engine_version:string;portfolio_rules_version:string;priority_run_fingerprint:string;matching_run_fingerprint:string;run_fingerprint:string;items:PortfolioItem[]};
export type PortfolioResponse = {profile_id:number;status:"NOT_SYNCED"|"READY";persistence_version:string|null;input_assembly_version:string|null;history_count:number;current_run:PortfolioRun|null;integrity:{ok:boolean}};
const buckets=["SAFE","TARGET","AMBITIOUS"] as const, dispositions=["INCLUDED","EXCLUDED"], priorities=["URGENT","HIGH","MEDIUM","LOW","IGNORE"], eligibility=["ELIGIBLE","UNKNOWN","INELIGIBLE"], lanes=["PRIMARY","UNCERTAIN","OUTSIDE_PREFERENCES"];
const obj=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const nonnegative=(v:unknown):v is number=>Number.isInteger(v)&&typeof v==="number"&&v>=0;
const fingerprint=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);
function validItem(v:unknown):v is PortfolioItem {if(!obj(v)||!obj(v.opportunity)||!obj(v.portfolio))return false;const o=v.opportunity,p=v.portfolio;if(!nonnegative(v.opportunity_id)||v.opportunity_id!==o.id||!nonnegative(o.id)||typeof o.canonical_title!=="string"||typeof o.organization!=="string"||!(o.location===null||typeof o.location==="string")||typeof o.last_seen_at!=="string"||typeof o.original_url!=="string"||!dispositions.includes(p.disposition as string)||!(p.bucket===null||buckets.includes(p.bucket as PortfolioBucket))||!(p.priority_category===null||priorities.includes(p.priority_category as string))||!eligibility.includes(p.eligibility_status as string)||!lanes.includes(p.matching_lane as string)||!nonnegative(p.required_skill_matched_count)||!nonnegative(p.required_skill_total_count)||typeof p.safe_cap_applied!=="boolean"||!Array.isArray(p.reason_codes)||!p.reason_codes.every(x=>typeof x==="string")||!fingerprint(p.assessment_fingerprint)||!obj(p.explanation))return false;if((p.disposition==="INCLUDED")!==(p.bucket!==null)||p.required_skill_matched_count>p.required_skill_total_count)return false;return p.required_skill_total_count===0?p.required_skill_matched_count===0&&p.required_skill_score===null:typeof p.required_skill_score==="number"&&Number.isFinite(p.required_skill_score)&&Math.round(p.required_skill_score*1e12)===Math.round((p.required_skill_matched_count/p.required_skill_total_count)*1e12);}
function validRun(v:unknown):v is PortfolioRun {if(!obj(v)||!obj(v.bucket_counts)||!Array.isArray(v.items)||!nonnegative(v.assessment_count)||!nonnegative(v.included_count)||!nonnegative(v.excluded_count))return false;const counts=v.bucket_counts;const strings=["created_at","persistence_version","input_assembly_version","portfolio_engine_version","portfolio_rules_version"] as const;return [v.run_id,v.priority_run_id,v.matching_run_id].every(x=>Number.isInteger(x)&&typeof x==="number"&&x>0)&&strings.every(k=>typeof v[k]==="string")&&[v.priority_run_fingerprint,v.matching_run_fingerprint,v.run_fingerprint].every(fingerprint)&&Object.keys(counts).length===3&&buckets.every(k=>nonnegative(counts[k]))&&v.items.length===v.assessment_count&&v.included_count+v.excluded_count===v.assessment_count&&buckets.reduce((n,k)=>n+(counts[k] as number),0)===v.included_count&&v.items.every(validItem);}
function valid(v:unknown):v is PortfolioResponse {if(!obj(v)||!obj(v.integrity)||v.integrity.ok!==true||!Number.isInteger(v.profile_id)||(v.profile_id as number)<=0||!nonnegative(v.history_count)||!(v.persistence_version===null||typeof v.persistence_version==="string")||!(v.input_assembly_version===null||typeof v.input_assembly_version==="string"))return false;return v.status==="NOT_SYNCED"?v.current_run===null:v.status==="READY"&&validRun(v.current_run);}
export async function getPortfolio():Promise<PortfolioResponse>{const base=(process.env.OPPORTUNITY_API_BASE_URL??API_BASE).replace(/\/$/,"");const response=await fetch(`${base}/api/portfolio`,{cache:"no-store",signal:AbortSignal.timeout(5_000)});if(!response.ok)throw new Error("Portfolio API request failed");const payload:unknown=await response.json();if(!valid(payload))throw new Error("Portfolio API response is invalid");return payload;}
export async function loadPortfolio():Promise<PortfolioResponse|null>{try{return await getPortfolio();}catch{return null;}}
