import "server-only";

const API_BASE = "http://127.0.0.1:8000";
export type PriorityCategory = "URGENT" | "HIGH" | "MEDIUM" | "LOW" | "IGNORE" | null;
export type PriorityEligibilityStatus = "ELIGIBLE" | "INELIGIBLE" | "UNKNOWN";
export type PriorityMatchingLane = "PRIMARY" | "UNCERTAIN" | "OUTSIDE_PREFERENCES";
export type PriorityOpportunity = { id:number; canonical_title:string; organization:string; location:string|null; last_seen_at:string; original_url:string };
export type PrioritySnapshot = { category:PriorityCategory; priority_score:number|null; priority_evidence_coverage:number; eligibility_status:PriorityEligibilityStatus; matching_lane:PriorityMatchingLane; assessment_fingerprint:string; published_at:string|null; deadline:string|null; deadline_status:string; reason_codes:string[]; hard_blocker:string|null; coverage_guardrail_applied:boolean; outside_preferences_cap_applied:boolean; urgent_promotion_applied:boolean; explanation:Record<string,unknown> };
export type PriorityItem = { opportunity_id:number; opportunity:PriorityOpportunity; priority:PrioritySnapshot };
export type PriorityRun = { run_id:number; matching_run_id:number; evaluation_date:string; created_at:string; assessment_count:number; persistence_version:string; input_assembly_version:string; priority_engine_version:string; priority_rules_version:string; freshness_version:string; quality_version:string; matching_run_fingerprint:string; run_fingerprint:string; category_counts:Record<"URGENT"|"HIGH"|"MEDIUM"|"LOW"|"IGNORE"|"NONE",number>; items:PriorityItem[] };
export type PriorityResponse = { profile_id:number; status:"NOT_SYNCED"|"READY"; persistence_version:string|null; input_assembly_version:string|null; history_count:number; current_run:PriorityRun|null; integrity:{ok:boolean} };
const categories = ["URGENT","HIGH","MEDIUM","LOW","IGNORE","NONE"] as const;
const cat = categories.slice(0,5);
const lanes = ["PRIMARY","UNCERTAIN","OUTSIDE_PREFERENCES"];
const eligibility = ["ELIGIBLE","INELIGIBLE","UNKNOWN"];
const obj=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const strNull=(v:unknown)=>typeof v==="string"||v===null;
const finite=(v:unknown)=>typeof v==="number"&&Number.isFinite(v);
function item(v:unknown):v is PriorityItem { if(!obj(v)||!obj(v.opportunity)||!obj(v.priority))return false; const o=v.opportunity,p=v.priority; return Number.isInteger(v.opportunity_id)&&Number.isInteger(o.id)&&typeof o.canonical_title==="string"&&typeof o.organization==="string"&&strNull(o.location)&&typeof o.last_seen_at==="string"&&typeof o.original_url==="string"&&(p.category===null||cat.includes(p.category as never))&&(p.priority_score===null||finite(p.priority_score))&&finite(p.priority_evidence_coverage)&&eligibility.includes(p.eligibility_status as string)&&lanes.includes(p.matching_lane as string)&&typeof p.assessment_fingerprint==="string"&&strNull(p.published_at)&&strNull(p.deadline)&&typeof p.deadline_status==="string"&&Array.isArray(p.reason_codes)&&p.reason_codes.every(x=>typeof x==="string")&&strNull(p.hard_blocker)&&[p.coverage_guardrail_applied,p.outside_preferences_cap_applied,p.urgent_promotion_applied].every(x=>typeof x==="boolean")&&obj(p.explanation); }
function run(v:unknown):v is PriorityRun { if(!obj(v)||!obj(v.category_counts)||!Array.isArray(v.items))return false; const c=v.category_counts; const count=Number.isInteger(v.assessment_count)&&typeof v.assessment_count==="number"?v.assessment_count:-1; return Number.isInteger(v.run_id)&&Number.isInteger(v.matching_run_id)&&["evaluation_date","created_at","persistence_version","input_assembly_version","priority_engine_version","priority_rules_version","freshness_version","quality_version","matching_run_fingerprint","run_fingerprint"].every(k=>typeof v[k]==="string")&&count>=0&&Object.keys(c).length===6&&categories.every(k=>Number.isInteger(c[k])&&(c[k] as number)>=0)&&categories.reduce((n,k)=>n+(c[k] as number),0)===count&&v.items.length===count&&v.items.every(item); }
function valid(v:unknown):v is PriorityResponse { if(!obj(v)||!obj(v.integrity)||!Number.isInteger(v.profile_id)||(v.profile_id as number)<=0||!Number.isInteger(v.history_count)||(v.history_count as number)<0||!strNull(v.persistence_version)||!strNull(v.input_assembly_version)||typeof v.integrity.ok!=="boolean")return false; return v.status==="READY"?v.integrity.ok===true&&run(v.current_run):v.status==="NOT_SYNCED"&&v.current_run===null; }
export async function getPriority():Promise<PriorityResponse>{ const base=(process.env.OPPORTUNITY_API_BASE_URL??API_BASE).replace(/\/$/,""); const response=await fetch(`${base}/api/priority`,{cache:"no-store",signal:AbortSignal.timeout(5_000)}); if(!response.ok)throw new Error("Priority API request failed"); const payload:unknown=await response.json(); if(!valid(payload))throw new Error("Priority API response is invalid"); return payload; }
export async function loadPriority():Promise<PriorityResponse|null>{try{return await getPriority();}catch{return null;}}
