import Link from "next/link";
import React from "react";
import {loadPriority,type PriorityItem,type PriorityMatchingLane,type PriorityResponse} from "@/lib/priority";
export const dynamic="force-dynamic";
const keys=["URGENT","HIGH","MEDIUM","LOW","IGNORE","NONE"] as const;
const labels={URGENT:"Urgente",HIGH:"Élevée",MEDIUM:"Moyenne",LOW:"Faible",IGNORE:"À ignorer",NONE:"Non classée"};
const lane:Record<PriorityMatchingLane,string>={PRIMARY:"Dans vos préférences de type",UNCERTAIN:"Compatibilité de type incertaine",OUTSIDE_PREFERENCES:"Hors préférences de type"};
const eligible={ELIGIBLE:"Éligible",INELIGIBLE:"Non éligible",UNKNOWN:"Inconnue / incertaine"};
const messages:Record<string,string>={DEADLINE_IMMINENT:"Deadline imminente",URGENT_PROMOTION:"Promotion en priorité urgente appliquée",OUTSIDE_PREFERENCES_CAP:"Priorité plafonnée car l’opportunité est hors préférences",KNOWN_ELIGIBILITY_BLOCKER:"Eligibility bloquante",COVERAGE_HIGH_GUARDRAIL:"Couverture insuffisante pour une priorité élevée",DEADLINE_EXPIRED_BLOCKER:"Deadline expirée"};
const percent=(v:number|null)=>v===null?"Indisponible":`${Math.round(v*100)} %`;
const rec=(v:unknown):Record<string,unknown>|null=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:null;
function Card({item}:{item:PriorityItem}){const p=item.priority,e=p.explanation; const components=[["Matching",rec(e.match)?.score],["Fraîcheur",rec(e.freshness)?.score],["Qualité de publication",rec(e.opportunity_quality)?.score],["Eligibility",p.eligibility_status],["Couverture des preuves",p.priority_evidence_coverage]];return <article className="matching-card"><p className="organization">{item.opportunity.organization}</p><h3>{item.opportunity.canonical_title}</h3><p className="location">{item.opportunity.location??"Lieu non précisé"}</p><span className="matching-badge">{labels[p.category??"NONE"]}</span><div className="matching-scores"><p><strong>Priority score</strong><span>{percent(p.priority_score)}</span></p><p><strong>Priority evidence coverage</strong><span>{percent(p.priority_evidence_coverage)}</span></p><p><strong>Eligibility</strong><span>{eligible[p.eligibility_status]}</span></p><p><strong>Matching lane</strong><span>{lane[p.matching_lane]}</span></p></div>{p.deadline&&<p>Deadline : {p.deadline}</p>}<p>Statut deadline : {p.deadline_status}</p><details className="matching-details"><summary>Pourquoi cette priorité ?</summary>{components.map(([name,value])=><p key={name as string}><strong>{name as string}</strong> : {typeof value==="number"?percent(value):String(value??"Indisponible")}</p>)}{p.reason_codes.filter(c=>messages[c]).map(c=><p key={c}>{messages[c]}</p>)}</details><a href={item.opportunity.original_url} target="_blank" rel="noreferrer">Voir l’offre originale</a></article>}
function Ready({data}:{data:PriorityResponse}){const run=data.current_run!;return <><section className="matching-summary"><div className="section-heading"><div><h2>Priorités prêtes</h2><p>{run.assessment_count} opportunités évaluées</p></div><p>Évaluation : {run.evaluation_date} · {data.history_count} snapshot{data.history_count>1?"s":""}</p></div><dl>{keys.map(k=><div key={k}><dt>{labels[k]}</dt><dd>{run.category_counts[k]}</dd></div>)}</dl></section><div>{keys.map(k=>{const items=run.items.filter(i=>(i.priority.category??"NONE")===k);const section=<section aria-labelledby={`priority-${k}`}><div className="section-heading"><h2 id={`priority-${k}`}>{labels[k]}</h2><p>{items.length}</p></div>{items.length?<div className="opportunity-grid">{items.map(i=><Card key={i.opportunity_id} item={i}/>)}</div>:<div className="status-panel"><p>Aucune opportunité dans cette section.</p></div>}</section>;return ["LOW","IGNORE","NONE"].includes(k)?<details className="matching-lane-collapsible" key={k}><summary>{labels[k]} ({items.length})</summary>{section}</details>:<React.Fragment key={k}>{section}</React.Fragment>})}</div><details className="technical-details"><summary>Détails techniques</summary><dl>{(["run_id","matching_run_id","evaluation_date","created_at","persistence_version","input_assembly_version","priority_engine_version","priority_rules_version","freshness_version","quality_version","run_fingerprint","matching_run_fingerprint"] as const).map(k=><React.Fragment key={k}><dt>{k}</dt><dd>{run[k]}</dd></React.Fragment>)}<dt>audit status</dt><dd>OK</dd></dl></details></>}
export default async function PriorityPage(){const data=await loadPriority();return <main className="page-shell"><header className="hero"><div><p className="eyebrow">Priorisation des opportunités</p><h1>Priorités</h1><p className="subtitle">Les opportunités classées à partir du dernier snapshot Priority audité.</p></div><Link className="health-link" href="/">Retour aux opportunités</Link></header>{data===null?<section className="status-panel" role="status"><h2>Priorités temporairement indisponibles</h2></section>:data.status==="NOT_SYNCED"?<section className="status-panel" role="status"><h2>Priorités à synchroniser</h2><p>Aucun classement Priority ne correspond au profil actuel. Lancez la synchronisation pour en obtenir un.</p></section>:<Ready data={data}/>}</main>}
