import Link from "next/link";
import React from "react";
import {loadPortfolio,type PortfolioBucket,type PortfolioItem,type PortfolioResponse} from "@/lib/portfolio";
export const dynamic="force-dynamic";
const buckets:[PortfolioBucket,string][]=[["SAFE","Safe"],["TARGET","Target"],["AMBITIOUS","Ambitious"]];
const eligibility={ELIGIBLE:"Éligible",UNKNOWN:"Inconnue / incertaine",INELIGIBLE:"Non éligible"};
function Reasons({item}:{item:PortfolioItem}){return item.portfolio.reason_codes.length?<details className="matching-details"><summary>Raisons persistées</summary>{item.portfolio.reason_codes.map(code=><p key={code}>{code}</p>)}</details>:null;}
function Card({item,excluded=false}:{item:PortfolioItem;excluded?:boolean}){const p=item.portfolio;return <article className="matching-card"><p className="organization">{item.opportunity.organization}</p><h3>{item.opportunity.canonical_title}</h3>{item.opportunity.location&&<p className="location">{item.opportunity.location}</p>}{!excluded&&<span className="matching-badge">{p.bucket}</span>}<div className="matching-scores"><p><strong>Priority</strong><span>{p.priority_category??"Non classée"}</span></p><p><strong>Eligibility</strong><span>{eligibility[p.eligibility_status]}</span></p><p><strong>Matching</strong><span>{p.matching_lane}</span></p>{!excluded&&<p><strong>Compétences requises</strong><span>{p.required_skill_total_count>0?`${p.required_skill_matched_count} / ${p.required_skill_total_count} compétences requises (${Math.round(p.required_skill_score!*100)} %)` : "Preuve de couverture non disponible"}</span></p>}</div><Reasons item={item}/><a href={item.opportunity.original_url} target="_blank" rel="noreferrer">Voir l’offre originale</a></article>}
function Ready({data}:{data:PortfolioResponse}){const run=data.current_run!,byId=(a:PortfolioItem,b:PortfolioItem)=>a.opportunity_id-b.opportunity_id,included=run.items.filter(i=>i.portfolio.disposition==="INCLUDED").sort(byId),excluded=run.items.filter(i=>i.portfolio.disposition==="EXCLUDED").sort(byId);return <><section className="matching-summary"><div className="section-heading"><div><h2>Portfolio actuel</h2><p>{run.assessment_count} opportunités évaluées</p></div></div><dl><div><dt>Included</dt><dd>{run.included_count}</dd></div><div><dt>Excluded</dt><dd>{run.excluded_count}</dd></div>{buckets.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{run.bucket_counts[key]}</dd></div>)}</dl></section>{buckets.map(([key,label])=>{const items=included.filter(i=>i.portfolio.bucket===key);return <section key={key} aria-labelledby={`portfolio-${key}`}><div className="section-heading"><h2 id={`portfolio-${key}`}>{label}</h2><p>{items.length}</p></div>{items.length?<div className="opportunity-grid">{items.map(i=><Card key={i.opportunity_id} item={i}/>)}</div>:<div className="status-panel"><p>Aucune opportunité dans ce groupe.</p></div>}</section>})}<details className="matching-lane-collapsible"><summary>Opportunités hors Portfolio actuel ({excluded.length})</summary><div className="section-heading"><h2>Opportunités hors Portfolio actuel</h2><p>{excluded.length}</p></div><div className="opportunity-grid">{excluded.map(i=><Card key={i.opportunity_id} item={i} excluded/>)}</div></details></>}
export default async function PortfolioPage(){const data=await loadPortfolio();return <main className="page-shell"><header className="hero"><div><p className="eyebrow">Position stratégique</p><h1>Portfolio</h1><p className="subtitle">Le dernier snapshot Portfolio persisté et audité.</p></div><Link className="health-link" href="/">Retour aux opportunités</Link></header>{data===null?<section className="status-panel" role="status"><h2>Portfolio temporairement indisponible</h2></section>:data.status==="NOT_SYNCED"?<section className="status-panel" role="status"><h2>Portfolio à synchroniser</h2><p>Aucun Portfolio ne correspond au profil actuel. Lancez la synchronisation pour en obtenir un.</p></section>:<Ready data={data}/>}</main>}
