"""Public deterministic Phase 4 matching contracts."""

from .component_audit import (
    COMPONENT_AUDIT_SELECTION_VERSION,
    COMPONENT_AUDIT_VERSION,
    AlignmentSummary,
    ComponentAuditInputError,
    ComponentAuditReport,
    Correlation,
    MatchingComponentObservation,
    NumericDistribution,
    SemanticSummary,
    SkillSummary,
    StructuredSummary,
    audit_matching_components,
    audit_matching_database,
    numeric_distribution,
    pearson_correlation,
)
from .component_audit_fingerprint import (
    canonical_component_audit_payload,
    canonical_component_observation_payload,
    component_audit_fingerprint,
    component_observation_fingerprint,
)

from .fingerprint import canonical_matching_payload, matching_input_fingerprint
from .inputs import (
    MatchingInputError,
    load_matching_input,
    load_opportunity_matching_input,
    load_profile_matching_input,
)
from .models import (
    MATCHING_INPUT_VERSION,
    MatchingInput,
    MatchingOpportunityInput,
    MatchingProfileInput,
)
from .role_domain_preferences import (
    DOMAIN_PREFERENCE_BRIDGE_VERSION,
    OPPORTUNITY_TYPE_BRIDGE_VERSION,
    ROLE_DOMAIN_PREFERENCES_VERSION,
    WORK_MODE_BRIDGE_VERSION,
    AlignmentReason,
    AlignmentStatus,
    DomainPreferenceAlignment,
    OpportunityTypeAlignment,
    RoleDomainPreferencesInputError,
    RoleDomainPreferencesResult,
    WorkModeAlignment,
    build_role_domain_preference_signals,
)
from .role_domain_preferences_fingerprint import (
    canonical_role_domain_preferences_payload,
    role_domain_preferences_fingerprint,
)
from .skill_signals import (
    SKILL_SIGNAL_VERSION,
    OpportunitySkillSignal,
    OpportunitySkillSignals,
    RequirementsState,
    SkillSignalKind,
    SkillSignalSource,
    build_opportunity_skill_signals,
)
from .skill_fit import (
    SKILL_FIT_VERSION,
    SkillCoverage,
    SkillFitEvaluation,
    SkillFitInputError,
    SkillFitResult,
    build_skill_fit,
)
from .skill_fit_fingerprint import canonical_skill_fit_payload, skill_fit_fingerprint
from .tfidf_fingerprint import (
    canonical_semantic_corpus_payload,
    canonical_semantic_similarity_payload,
    semantic_corpus_fingerprint,
    semantic_similarity_fingerprint,
    tfidf_model_fingerprint,
)
from .tfidf_similarity import (
    SEMANTIC_DOCUMENT_VERSION,
    TFIDF_VERSION,
    FittedTfidfCorpus,
    OpportunitySemanticDocument,
    ProfileSemanticDocument,
    SemanticOverlapTerm,
    SemanticSimilarityInputError,
    SemanticSimilarityResult,
    SemanticSimilarityStatus,
    build_opportunity_semantic_document,
    build_profile_semantic_document,
    fit_tfidf_corpus,
    score_matching_input_semantic_similarity,
    score_profile_against_tfidf_corpus,
)

__all__ = [
    "COMPONENT_AUDIT_SELECTION_VERSION",
    "COMPONENT_AUDIT_VERSION",
    "AlignmentSummary",
    "ComponentAuditInputError",
    "ComponentAuditReport",
    "Correlation",
    "MatchingComponentObservation",
    "NumericDistribution",
    "SemanticSummary",
    "SkillSummary",
    "StructuredSummary",
    "audit_matching_components",
    "audit_matching_database",
    "numeric_distribution",
    "pearson_correlation",
    "canonical_component_audit_payload",
    "canonical_component_observation_payload",
    "component_audit_fingerprint",
    "component_observation_fingerprint",
    "MATCHING_INPUT_VERSION",
    "ROLE_DOMAIN_PREFERENCES_VERSION",
    "OPPORTUNITY_TYPE_BRIDGE_VERSION",
    "DOMAIN_PREFERENCE_BRIDGE_VERSION",
    "WORK_MODE_BRIDGE_VERSION",
    "AlignmentReason",
    "AlignmentStatus",
    "DomainPreferenceAlignment",
    "OpportunityTypeAlignment",
    "RoleDomainPreferencesInputError",
    "RoleDomainPreferencesResult",
    "WorkModeAlignment",
    "MatchingInput",
    "MatchingInputError",
    "MatchingOpportunityInput",
    "MatchingProfileInput",
    "OpportunitySkillSignal",
    "OpportunitySkillSignals",
    "RequirementsState",
    "SKILL_FIT_VERSION",
    "SKILL_SIGNAL_VERSION",
    "SEMANTIC_DOCUMENT_VERSION",
    "TFIDF_VERSION",
    "FittedTfidfCorpus",
    "OpportunitySemanticDocument",
    "ProfileSemanticDocument",
    "SemanticOverlapTerm",
    "SemanticSimilarityInputError",
    "SemanticSimilarityResult",
    "SemanticSimilarityStatus",
    "SkillSignalKind",
    "SkillSignalSource",
    "SkillCoverage",
    "SkillFitEvaluation",
    "SkillFitInputError",
    "SkillFitResult",
    "build_opportunity_skill_signals",
    "build_role_domain_preference_signals",
    "build_skill_fit",
    "build_opportunity_semantic_document",
    "build_profile_semantic_document",
    "fit_tfidf_corpus",
    "score_matching_input_semantic_similarity",
    "score_profile_against_tfidf_corpus",
    "canonical_semantic_corpus_payload",
    "canonical_semantic_similarity_payload",
    "semantic_corpus_fingerprint",
    "semantic_similarity_fingerprint",
    "tfidf_model_fingerprint",
    "canonical_matching_payload",
    "canonical_role_domain_preferences_payload",
    "canonical_skill_fit_payload",
    "load_matching_input",
    "load_opportunity_matching_input",
    "load_profile_matching_input",
    "matching_input_fingerprint",
    "role_domain_preferences_fingerprint",
    "skill_fit_fingerprint",
]
